"""Add hazards and relocation_sites

Revision ID: 3d9b0d74d334
Revises: 9a7a11155d0c
Create Date: 2026-09-13 01:21:12.476681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3d9b0d74d334'
down_revision: Union[str, None] = '9a7a11155d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazards',
    sa.Column('hazard_type', sa.String(length=100), nullable=False),
    sa.Column('intensity', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('date_recorded', sa.String(length=50), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazards_hazard_type'), 'hazards', ['hazard_type'], unique=False)
    op.create_index(op.f('ix_hazards_id'), 'hazards', ['id'], unique=False)
    op.create_table('relocation_sites',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('facility_type', sa.String(length=100), nullable=False, comment='e.g., School, Community Hall, Open Ground'),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('water_available', sa.Boolean(), nullable=False),
    sa.Column('sanitation_available', sa.Boolean(), nullable=False),
    sa.Column('medical_facilities', sa.Boolean(), nullable=False),
    sa.Column('electricity_available', sa.Boolean(), nullable=False),
    sa.Column('kitchen_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('site_suitability_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relocation_sites_district_id'), 'relocation_sites', ['district_id'], unique=False)
    op.create_index(op.f('ix_relocation_sites_id'), 'relocation_sites', ['id'], unique=False)
    op.create_index(op.f('ix_relocation_sites_name'), 'relocation_sites', ['name'], unique=False)
    op.create_table('settlements',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('tehsil_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('population_density', sa.Float(), nullable=False),
    sa.Column('vulnerable_population', sa.Integer(), nullable=False),
    sa.Column('elderly_population', sa.Integer(), nullable=False),
    sa.Column('children_population', sa.Integer(), nullable=False),
    sa.Column('disabled_population', sa.Integer(), nullable=False),
    sa.Column('road_access', sa.Boolean(), nullable=False),
    sa.Column('nearest_healthcare_distance', sa.Float(), nullable=False, comment='Distance in km'),
    sa.Column('nearest_shelter_distance', sa.Float(), nullable=False, comment='Distance in km'),
    sa.Column('nearest_school_distance', sa.Float(), nullable=False, comment='Distance in km'),
    sa.Column('water_access', sa.Boolean(), nullable=False),
    sa.Column('electricity_access', sa.Boolean(), nullable=False),
    sa.Column('sanitation_access', sa.Boolean(), nullable=False),
    sa.Column('current_hazard_status', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('vulnerability_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tehsil_id'], ['tehsils.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_block_id'), 'settlements', ['block_id'], unique=False)
    op.create_index(op.f('ix_settlements_current_hazard_status'), 'settlements', ['current_hazard_status'], unique=False)
    op.create_index(op.f('ix_settlements_district_id'), 'settlements', ['district_id'], unique=False)
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_index(op.f('ix_settlements_name'), 'settlements', ['name'], unique=False)
    op.create_index(op.f('ix_settlements_priority_level'), 'settlements', ['priority_level'], unique=False)
    op.create_index(op.f('ix_settlements_state_id'), 'settlements', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_tehsil_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_state_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_priority_level'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_name'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_district_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_current_hazard_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_block_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_relocation_sites_name'), table_name='relocation_sites')
    op.drop_index(op.f('ix_relocation_sites_id'), table_name='relocation_sites')
    op.drop_index(op.f('ix_relocation_sites_district_id'), table_name='relocation_sites')
    op.drop_table('relocation_sites')
    op.drop_index(op.f('ix_hazards_id'), table_name='hazards')
    op.drop_index(op.f('ix_hazards_hazard_type'), table_name='hazards')
    op.drop_table('hazards')
    # ### end Alembic commands ###
