"""add_ndrf_battalions_and_alerts

Revision ID: 86262f74f87a
Revises: 3d9b0d74d334
Create Date: 2026-09-29 22:18:57.849945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '86262f74f87a'
down_revision: Union[str, None] = '3d9b0d74d334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ndrf_battalions',
    sa.Column('battalion_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rrc_location', sa.String(length=500), nullable=False),
    sa.Column('headquarters', sa.String(length=255), nullable=False),
    sa.Column('commandant', sa.String(length=255), nullable=False),
    sa.Column('duty_officer', sa.String(length=255), nullable=False),
    sa.Column('operational_zone', sa.String(length=500), nullable=False),
    sa.Column('contact_eoc', sa.String(length=100), nullable=False),
    sa.Column('tactical_radio_net', sa.String(length=255), nullable=False),
    sa.Column('satellite_uplink', sa.String(length=255), nullable=False),
    sa.Column('personnel_strength', sa.Integer(), nullable=False),
    sa.Column('available_qrf_teams', sa.Integer(), nullable=False),
    sa.Column('deployed_teams', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndrf_battalions_battalion_code'), 'ndrf_battalions', ['battalion_code'], unique=True)
    op.create_index(op.f('ix_ndrf_battalions_id'), 'ndrf_battalions', ['id'], unique=False)
    op.create_table('ndrf_alerts',
    sa.Column('dispatch_id', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authority_level', sa.String(length=10), nullable=False),
    sa.Column('authority_label', sa.String(length=500), nullable=False),
    sa.Column('authorized_by', sa.String(length=500), nullable=False),
    sa.Column('battalion_id', sa.Integer(), nullable=False),
    sa.Column('battalion_code', sa.String(length=30), nullable=False),
    sa.Column('battalion_name', sa.String(length=255), nullable=False),
    sa.Column('priority_level', sa.String(length=60), nullable=False),
    sa.Column('priority_label', sa.String(length=255), nullable=False),
    sa.Column('settlement_ids', sa.JSON(), nullable=False),
    sa.Column('settlement_names', sa.JSON(), nullable=False),
    sa.Column('threatened_population', sa.Integer(), nullable=False),
    sa.Column('vulnerable_population', sa.Integer(), nullable=False),
    sa.Column('road_access_status', sa.String(length=500), nullable=False),
    sa.Column('recommended_route', sa.String(length=500), nullable=False),
    sa.Column('assigned_shelter_id', sa.Integer(), nullable=True),
    sa.Column('assigned_shelter_name', sa.String(length=255), nullable=False),
    sa.Column('assigned_shelter_capacity', sa.Integer(), nullable=False),
    sa.Column('tactical_units_requested', sa.JSON(), nullable=False),
    sa.Column('tactical_directive', sa.Text(), nullable=False),
    sa.Column('comms_channel', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active_teams_deployed', sa.Integer(), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['battalion_id'], ['ndrf_battalions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndrf_alerts_battalion_id'), 'ndrf_alerts', ['battalion_id'], unique=False)
    op.create_index(op.f('ix_ndrf_alerts_dispatch_id'), 'ndrf_alerts', ['dispatch_id'], unique=True)
    op.create_index(op.f('ix_ndrf_alerts_id'), 'ndrf_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_ndrf_alerts_status'), 'ndrf_alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndrf_alerts_status'), table_name='ndrf_alerts')
    op.drop_index(op.f('ix_ndrf_alerts_id'), table_name='ndrf_alerts')
    op.drop_index(op.f('ix_ndrf_alerts_dispatch_id'), table_name='ndrf_alerts')
    op.drop_index(op.f('ix_ndrf_alerts_battalion_id'), table_name='ndrf_alerts')
    op.drop_table('ndrf_alerts')
    op.drop_index(op.f('ix_ndrf_battalions_id'), table_name='ndrf_battalions')
    op.drop_index(op.f('ix_ndrf_battalions_battalion_code'), table_name='ndrf_battalions')
    op.drop_table('ndrf_battalions')
    # ### end Alembic commands ###
